require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ReactAudioPlayer' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
   pod 'Permission-Microphone', :path => '../node_modules/react-native-permissions/ios/Microphone'

  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'

end
